<%@ Page Title="" Language="C#" MasterPageFile="~/SitioWeb.Master" AutoEventWireup="true" CodeBehind="WebProgramacionSeries.aspx.cs" Inherits="WebApp.WebForms.Programacion.WebProgramacion" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Backup Series</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <asp:GridView ClientIDMode="Static" AutoGenerateColumns="false" DataKeyNames="ID_BACKUP_SERIE" ID="tabla_programacion_serie" runat="server" AllowPaging="true" CssClass="table table-hover text-nowrap"
                        OnPageIndexChanging="tabla_programacion_serie_PageIndexChanging" OnRowEditing="tabla_programacion_serie_RowEditing"
                        OnRowDeleting="tabla_programacion_serie_RowDeleting" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
                        <Columns>
                            <asp:BoundField HeaderText="ID_Backup_Serie" DataField="ID_BACKUP_SERIE" ReadOnly="true" />
                            <asp:BoundField HeaderText="Nombre" DataField="NOMBRE" />
                            <asp:BoundField HeaderText="Fecha_Backup" DataField="FECHA_BACKUP" />
                            <asp:BoundField HeaderText="Episodio_Min" DataField="CANTIDAD_EPISODIO_MIN" />
                            <asp:BoundField HeaderText="Episodio_Max" DataField="CANTIDAD_EPISODIO_MAX" />
                            <asp:BoundField HeaderText="Observaciones" DataField="OBSERVACIONES" />
                            <asp:BoundField HeaderText="Tipo_Serie" DataField="TIPO_SERIE" />
                            <asp:BoundField HeaderText="Casa_Productora" DataField="CASA_PRODUCTORA" />
                            <asp:BoundField HeaderText="Ubicacion_Cinta " DataField="UBICACION_CINTA" />
                            <asp:TemplateField HeaderText="Estado">
                                <ItemTemplate>
                                    <%# (string)Eval("ESTADO")=="COMPLETO" ? "<span class=\"badge bg-success\">COMPLETO</span>" : "<span class=\"badge bg-warning\">EN BLOQUES</span>" %>                                                                       
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <asp:LinkButton runat="server" CommandName="Edit" CssClass="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i> Editar</asp:LinkButton>
                                    <asp:LinkButton runat="server" CommandName="Delete" CssClass="btn btn-danger btn-sm" OnClientClick=""><i class="fas fa-trash"></i> Eliminar</asp:LinkButton>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <PagerSettings Mode="NumericFirstLast" PageButtonCount="10" />
                    </asp:GridView>
                </div>
            </div>
            <!-- /.card -->

            </div>
    </div>
    <!-- /.row -->
</asp:Content>
