<%@ Page Title="" Language="C#" MasterPageFile="~/SitioWeb.Master" AutoEventWireup="true" CodeBehind="WebProgramacionPeliculas.aspx.cs" Inherits="WebApp.WebForms.Programacion.WebProgramacionPeliculas" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <link rel="stylesheet" runat="server" href="../../plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" />
    <!-- Select2 -->
    <link rel="stylesheet" href="../../plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="../../plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <script src="../../plugins/select2/js/select2.full.min.js"></script>
    <script src="../../plugins/jquery/jquery.min.js"></script>

    <script = "text/javascript" >        
        function confirmarEliminar() {
            var respuesta = confirm("¿Deseas eliminar el registro?");

            if (respuesta == true) {
                return true;
            } else {
                return false;
            }
        }

        function limpiarInputsR() {
            document.getElementById('<%=txtObservaciones.ClientID%>').value = '';

           $('#modalRegistrar').modal('hide');
        }

        function limpiarFormBusqueda() {
            document.getElementById('<%=NomBusqueda.Value%>').value = '';
            document.getElementById('<%=FechaBusqueda.Value%>').value = '';
            document.getElementById('<%=CasaBusqueda.Value%>').value = '';
            document.getElementById('<%=UbicacionBusqueda.Value%>').value = '';

            $('#modalBuscar').modal('hide');
        }
        //Initialize Select2 Elements
        $(document).ready(function () {
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
        });
        
    </script> 
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Backup Peliculas</h3>
                    <br />
                    <br />
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalRegistrar">Registrar</button>
                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 100px;">
                            <%--<input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>--%>
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalBuscar">
                                <i class="fas fa-search"></i> Buscar</button>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <asp:GridView ClientIDMode="Static" AutoGenerateColumns="false" DataKeyNames="ID_BACKUP_PELICULA" ID="tabla_programacion_pelicula" runat="server" AllowPaging="true" CssClass="table table-hover text-nowrap"
                        OnPageIndexChanging="tabla_programacion_pelicula_PageIndexChanging" OnRowEditing="tabla_programacion_pelicula_RowEditing"
                        OnRowDeleting="tabla_programacion_pelicula_RowDeleting" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
                        <Columns>
                            <asp:BoundField HeaderText="ID" DataField="ID_BACKUP_PELICULA" ReadOnly="true" />
                            <asp:BoundField HeaderText="Nombre" DataField="NOMBRE_PELICULA" />
                            <asp:BoundField HeaderText="Fecha Guardada" DataField="FECHA_BACKUP" />
                            <asp:BoundField HeaderText="Observaciones" DataField="OBSERVACIONES" />
                            <asp:BoundField HeaderText="Casa Productora" DataField="CASA_PRODUCTORA" />
                            <asp:BoundField HeaderText="Ubicacion Cinta " DataField="UBICACION_CINTA" />
                            <asp:TemplateField HeaderText="Estado">
                                <ItemTemplate>
                                    <%# (string)Eval("ESTADO")=="COMPLETO" ? "<span class=\"badge bg-success\">COMPLETO</span>" : "<span class=\"badge bg-warning\">EN BLOQUES</span>" %>                                                                       
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <asp:LinkButton runat="server" CommandName="Edit" CssClass="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i> Editar</asp:LinkButton>
                                    <asp:LinkButton runat="server" CommandName="Delete" CssClass="btn btn-danger btn-sm" OnClientClick="return confirmarEliminar();"><i class="fas fa-trash"></i> Eliminar</asp:LinkButton>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <PagerSettings Mode="NumericFirstLast" PageButtonCount="10" />
                    </asp:GridView>
                </div>
            </div>
            <!-- /.card -->
        </div>
    </div>
    <!-- /.row -->
    <!--modal-content -->
    <div class="modal fade" id="modalRegistrar" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">

                <asp:Panel ID="pnlPeliculasRegister" runat="server" DefaultButton="btnRegistrar">
                    <div class="modal-header">
                    <h4 class="modal-title">Nuevo Registro</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="">Nombre de Pelicula:</label>
                        <asp:DropDownList ID="ddlNombreMaterial" runat="server" CssClass="select2bs4">
                            
                        </asp:DropDownList>
                    </div>                    
                    <div class="form-group">
                        <label for="txtObservaciones">Observacion:</label>
                        <textarea runat="server" id="txtObservaciones" cols="20" rows="3" class="form-control"></textarea>
                    </div>
                    <%--<div class="form-group">
                        <label for="">Tipo de Pelicula:</label>
                        <asp:DropDownList ID="ddlTipoSerie" runat="server" CssClass="form-control">
                            
                        </asp:DropDownList>
                    </div>--%>
                    <div class="form-group">
                        <label for="">Casa Productora:</label>
                        <asp:DropDownList ID="ddlCasaProductora" runat="server" CssClass="select2bs4">
                            
                        </asp:DropDownList>
                    </div>
                    <div class="form-group">
                        <label for="">Ubicacion Cinta:</label>
                        <asp:DropDownList ID="ddlUbicacion" runat="server" CssClass="select2bs4">
                            
                        </asp:DropDownList>
                    </div>
                    <div class="form-group">
                        <label for="">Estado:</label>
                        <asp:DropDownList ID="ddlEstado" runat="server" CssClass="form-control">
                            <asp:ListItem Value="1" Text="COMPLETO"></asp:ListItem>
                            <asp:ListItem Value="0" Text="EN BLOQUES"></asp:ListItem>
                        </asp:DropDownList>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="limpiarInputsR()">Cancelar</button>
                    <asp:Button ID="btnRegistrar" runat="server" Text="Guardar" CssClass="btn btn-primary" OnClick="btnRegistrar_Click" />
                </div>
                </asp:Panel>
                
            </div>

        </div>
    </div>
    <!-- /.modal-content -->

    <!--modal-content -->
    <div class="modal fade" id="modalEditar" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">

                <asp:Panel ID="pnlPeliculasEdit" runat="server" DefaultButton="btnActualizar">
                    <div class="modal-header">
                    <h4 class="modal-title">Editar Registro</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="">Nombre de Pelicula:</label>
                        <asp:DropDownList ID="ddlNombreEditar" runat="server" CssClass="form-control select2bs4">
                            
                        </asp:DropDownList>
                    </div>                   
                    <div class="form-group">
                        <label for="txtObserEditar">Observacion:</label>
                        <textarea runat="server" id="txtObserEditar" cols="20" rows="3" class="form-control"></textarea>
                    </div>
                    <%--<div class="form-group">
                        <label for="">Tipo de Pelicula:</label>
                        <asp:DropDownList ID="ddlTipoEditar" runat="server" CssClass="form-control">
                            
                        </asp:DropDownList>
                    </div>--%>
                    <div class="form-group">
                        <label for="">Casa Productora:</label>
                        <asp:DropDownList ID="ddlCasaEditar" runat="server" CssClass="form-control select2bs4">
                            
                        </asp:DropDownList>
                    </div>
                    <div class="form-group">
                        <label for="">Ubicacion Cinta:</label>
                        <asp:DropDownList ID="ddlUbicacionEditar" runat="server" CssClass="form-control select2bs4">
                            
                        </asp:DropDownList>
                    </div>
                    <div class="form-group">
                        <label for="">Estado:</label>
                        <asp:DropDownList ID="ddlEstadoEditar" runat="server" CssClass="form-control">
                        </asp:DropDownList>
                    </div>
                    <input runat="server" id="codBackupPelicula" type="hidden"/>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    <asp:Button ID="btnActualizar" runat="server" Text="Guardar" CssClass="btn btn-primary" OnClick="btnActualizar_Click" />
                </div>
                </asp:Panel>
                
            </div>
            
        </div>
    </div>
    <!-- /.modal-content -->

    <!--modal-content -->
    <div class="modal fade" id="modalBuscar" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Buscar Registros</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="NomBusqueda">Nombre Pelicula:</label>
                        <input runat="server" type="text" class="form-control" id="NomBusqueda" placeholder=""/>
                    </div>
                    <div class="form-group">
                        <label for="FechaBusqueda">Fecha:</label>
                        <input runat="server" type="date" class="form-control" id="FechaBusqueda" data-inputmask-alias="date" data-inputmask-inputformat="dd/mm/yyyy"/>
                    </div>
                    <div class="form-group">
                        <label for="CasaBusqueda">Casa Productora:</label>
                        <input runat="server" type="text" class="form-control" id="CasaBusqueda" placeholder=""/>
                    </div>                  
                    <div class="form-group">
                        <label for="UbicacionBusqueda">Ubicacion Cinta:</label>
                        <input runat="server" type="text" class="form-control" id="UbicacionBusqueda" placeholder=""/>
                    </div>                    
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger" onclick="limpiarFormBusqueda()" data-dismiss="modal">Cancelar</button>
                    <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="btn btn-primary" OnClick="btnBuscar_Click" />
                </div>
            </div>
        </div>
    </div>
    <!-- /.modal-content -->
    
</asp:Content>
