<%@ Page Title="" Language="C#" MasterPageFile="~/SitioWeb.Master" AutoEventWireup="true" CodeBehind="WebReporteSerie.aspx.cs" Inherits="WebApp.WebForms.Reportes.WebReporteSerie" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Reporte Backup Series</h3>

                    <%--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalRegistrar">Registrar</button>--%>
                    <div class="card-tools">
                        <%--<div class="input-group input-group-sm" style="width: 200px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>--%>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="form-group">
                        <label for="">Titulo del reporte</label>
                        <asp:TextBox ID="txtTituloReporte" runat="server" CssClass="form-control"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label for="">Nombre del archivo PDF</label>
                        <asp:TextBox ID="txtArchivopdf" runat="server" CssClass="form-control"></asp:TextBox>
                    </div>
                    <table style="" class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Serie</th>
                                <th>Estado</th>
                            </tr>
                        </thead>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                    <div class="card-body table-responsive p-0">
                        <%--<asp:GridView ClientIDMode="Static" AutoGenerateColumns="false" DataKeyNames="ID_BACKUP_SERIE" ID="" runat="server" AllowPaging="true" CssClass="table table-hover text-nowrap"
                        OnPageIndexChanging="" OnRowEditing=""
                        OnRowDeleting="" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
                        <Columns>
                            <asp:BoundField HeaderText="ID" DataField="ID_BACKUP_SERIE" ReadOnly="true" />
                            <asp:BoundField HeaderText="Nombre" DataField="NOMBRE_SERIE" />
                            <asp:BoundField HeaderText="Fecha Guardada" DataField="FECHA_BACKUP" />
                            <asp:BoundField HeaderText="Episodio Minimo" DataField="CANTIDAD_EPISODIO_MIN" />
                            <asp:BoundField HeaderText="Episodio Maximo" DataField="CANTIDAD_EPISODIO_MAX" />
                            <asp:BoundField HeaderText="Observaciones" DataField="OBSERVACIONES" />
                            <asp:BoundField HeaderText="Tipo de Serie" DataField="TIPO_SERIE" />
                            <asp:BoundField HeaderText="Casa Productora" DataField="CASA_PRODUCTORA" />
                            <asp:BoundField HeaderText="Ubicacion Cinta " DataField="UBICACION_CINTA" />
                            <asp:TemplateField HeaderText="Estado">
                                <ItemTemplate>
                                    <%# (string)Eval("ESTADO")=="COMPLETO" ? "<span class=\"badge bg-success\">COMPLETO</span>" : "<span class=\"badge bg-warning\">EN BLOQUES</span>" %>
                                </ItemTemplate>
                            </asp:TemplateField>                           
                        </Columns>
                        <PagerSettings Mode="NumericFirstLast" PageButtonCount="10" />
                    </asp:GridView>--%>
                    </div>
                    <asp:Button ID="btnGenerarPDF" runat="server" Text="Descargar" CssClass="btn btn-block btn-outline-primary" />
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
    <!-- /.row -->
    
</asp:Content>
