<%@ Page Title="" Language="C#" MasterPageFile="~/SitioWeb.Master" AutoEventWireup="true" CodeBehind="WebReporteSerie.aspx.cs" Inherits="WebApp.WebForms.Reportes.WebReporteSerie" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

     <script = "text/javascript" >
         
         function limpiarFormBusqueda() {
            document.getElementById('<%=NomBusqueda.Value %>').value = '';
            document.getElementById('<%=FechaBusqueda.Value %>').value = '';
            document.getElementById('<%=CasaBusqueda.Value %>').value = '';
            document.getElementById('<%=UbicacionBusqueda.Value %>').value = '';

            $('#modalBuscar').modal('hide');
         }

         function limpiarCampos() {
            setTimeout(function () {
                document.getElementById('<%= txtTituloReporte.ClientID %>').value = '';
                document.getElementById('<%= txtArchivopdf.ClientID %>').value = '';
            }, 1000);
         }
     </script> 
    <div class="row">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Reporte Backup Series</h3>

                    <div class="card-tools">
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="form-group">
                        <label for="">Titulo del reporte</label>
                        <asp:TextBox ID="txtTituloReporte" runat="server" CssClass="form-control"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label for="">Nombre del archivo PDF</label>
                        <asp:TextBox ID="txtArchivopdf" runat="server" CssClass="form-control"></asp:TextBox>
                    </div>
                    <br />
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalBuscar">
                                <i class="fas fa-search"></i> Buscar</button>
                    <br />
                    <br />
                    <div class="card-body table-responsive p-0">
                        <asp:GridView ClientIDMode="Static" AutoGenerateColumns="false" DataKeyNames="ID_BACKUP_SERIE" ID="tabla_reporte_programacion_serie" runat="server" AllowPaging="true" CssClass="table table-hover text-nowrap"
                        OnPageIndexChanging="tabla_reporte_programacion_serie_PageIndexChanging" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
                        <Columns>
                            <asp:BoundField HeaderText="ID" DataField="ID_BACKUP_SERIE" ReadOnly="true" />
                            <asp:BoundField HeaderText="Nombre" DataField="NOMBRE_SERIE" ReadOnly="true" />
                            <asp:BoundField HeaderText="Fecha Guardada" DataField="FECHA_BACKUP" ReadOnly="true" />
                            <asp:BoundField HeaderText="Episodio Minimo" DataField="CANTIDAD_EPISODIO_MIN" ReadOnly="true" />
                            <asp:BoundField HeaderText="Episodio Maximo" DataField="CANTIDAD_EPISODIO_MAX" ReadOnly="true" />
                            <asp:BoundField HeaderText="Observaciones" DataField="OBSERVACIONES" ReadOnly="true" />
                            <asp:BoundField HeaderText="Tipo de Serie" DataField="TIPO_SERIE" ReadOnly="true" />
                            <asp:BoundField HeaderText="Casa Productora" DataField="CASA_PRODUCTORA" ReadOnly="true" />
                            <asp:BoundField HeaderText="Ubicacion Cinta " DataField="UBICACION_CINTA" ReadOnly="true"/>
                            <asp:TemplateField HeaderText="Estado">
                                <ItemTemplate>
                                    <%# (string)Eval("ESTADO")=="COMPLETO" ? "<span class=\"badge bg-success\">COMPLETO</span>" : "<span class=\"badge bg-warning\">EN BLOQUES</span>" %>
                                </ItemTemplate>
                            </asp:TemplateField>                           
                        </Columns>
                        <PagerSettings Mode="NumericFirstLast" PageButtonCount="10" />
                    </asp:GridView>
                    </div>
                    <br />
                    <asp:LinkButton ID="btnIcono" runat="server" CssClass="btn btn-block btn-outline-primary" OnClick="btnGenerarPDF_Click" OnClientClick="limpiarCampos();">
                         <i class="fa fa-download"></i> Descargar PDF
                    </asp:LinkButton>
                    
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
    <!-- /.row -->
    
    <!--modal-content -->
    <div class="modal fade" id="modalBuscar" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">

                <asp:Panel ID="pnlBuscar" runat="server" DefaultButton="btnBuscar">
                    <div class="modal-header">
                    <h4 class="modal-title">Buscar Registros</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="NomBusqueda">Nombre Serie:</label>
                        <input runat="server" type="text" class="form-control" id="NomBusqueda" placeholder=""/>
                    </div>
                    <div class="form-group">
                        <label for="FechaBusqueda">Fecha:</label>
                        <input runat="server" type="date" class="form-control" id="FechaBusqueda" data-inputmask-alias="date" data-inputmask-inputformat="dd/mm/yyyy"/>
                    </div>
                    <div class="form-group">
                        <label for="CasaBusqueda">Casa Productora:</label>
                        <input runat="server" type="text" class="form-control" id="CasaBusqueda" placeholder=""/>
                    </div>                  
                    <div class="form-group">
                        <label for="UbicacionBusqueda">Ubicacion Cinta:</label>
                        <input runat="server" type="text" class="form-control" id="UbicacionBusqueda" placeholder=""/>
                    </div>                    
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger" onclick="limpiarFormBusqueda()" data-dismiss="modal">Cancelar</button>
                    <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="btn btn-primary" OnClick="btnBuscar_Click" />
                </div>
                </asp:Panel>
                
            </div>
        </div>
    </div>
    <!-- /.modal-content -->
</asp:Content>
