<%@ Page Title="" Language="C#" MasterPageFile="~/SitioWeb.Master" AutoEventWireup="true" CodeBehind="WebReportePeliculas.aspx.cs" Inherits="WebApp.WebForms.Reportes.WebReportePeliculas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <script = "text/javascript" > 
         function limpiarFormBusqueda() {
            document.getElementById('<%=NomBusqueda.Value%>').value = '';
            document.getElementById('<%=FechaBusqueda.Value%>').value = '';
            document.getElementById('<%=CasaBusqueda.Value%>').value = '';
            document.getElementById('<%=UbicacionBusqueda.Value%>').value = '';

            $('#modalBuscar').modal('hide');
        }

        function validarFormulario() {
            var titulo = document.getElementById('<%=txtTituloReporte.ClientID%>').value;
            var cambiarTitulo = document.getElementById('<%=txtTituloReporte.ClientID%>');
            var archivo = document.getElementById('<%=txtArchivopdf.ClientID%>').value;
            var cambiarArchivo = document.getElementById('<%=txtArchivopdf.ClientID%>');


            if (titulo.trim() === '' && archivo.trim() === '') {
                cambiarTitulo.classList.add('is-invalid');
                cambiarArchivo.classList.add('is-invalid');
                return false; // Evita que se envíe el formulario
            } else if (titulo.trim() != '' && archivo.trim() === '') {
                cambiarTitulo.classList.remove('is-invalid');
                cambiarArchivo.classList.add('is-invalid');
                return false;
            } else if (titulo.trim() === '' && archivo.trim() != '') {
                cambiarTitulo.classList.add('is-invalid');
                cambiarArchivo.classList.remove('is-invalid');
                return false;
            }
            // Si todos los campos son válidos, permitir el envío del formulario
            cambiarTitulo.classList.remove('is-invalid');
            cambiarArchivo.classList.remove('is-invalid');
            return true;
        }

        function limpiarCampos() {
             var tituloVer = document.getElementById('<%=txtTituloReporte.ClientID%>').value;
            var archivoVer = document.getElementById('<%=txtArchivopdf.ClientID%>').value;
            if (tituloVer.trim() != '' && archivoVer.trim() != '') {
                setTimeout(function () {
                    document.getElementById('<%= txtTituloReporte.ClientID %>').value = '';
                    document.getElementById('<%= txtArchivopdf.ClientID %>').value = '';
                }, 1500);
            }            
         }
     </script> 
    <div class="row">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Reporte Backup Peliculas</h3>

                    <div class="card-tools">
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="form-group">
                        <label for="">Titulo del reporte</label>
                        <asp:TextBox ID="txtTituloReporte" runat="server" CssClass="form-control"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label for="">Nombre del archivo PDF</label>
                        <asp:TextBox ID="txtArchivopdf" runat="server" CssClass="form-control"></asp:TextBox>
                    </div>
                    <br />
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalBuscar">
                                <i class="fas fa-search"></i> Buscar</button>
                    <br />
                    <br />
                    <div class="card-body table-responsive p-0">
                        <asp:GridView ClientIDMode="Static" AutoGenerateColumns="false" DataKeyNames="ID_BACKUP_PELICULA" ID="tabla__reporte_programacion_pelicula" runat="server" AllowPaging="true" CssClass="table table-hover text-nowrap"
                        OnPageIndexChanging="tabla__reporte_programacion_pelicula_PageIndexChanging" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false">
                        <Columns>
                            <asp:BoundField HeaderText="ID" DataField="ID_BACKUP_PELICULA" ReadOnly="true" />
                            <asp:BoundField HeaderText="Nombre" DataField="NOMBRE_PELICULA" ReadOnly="true" />
                            <asp:BoundField HeaderText="Fecha Guardada" DataField="FECHA_BACKUP" ReadOnly="true" />
                            <asp:BoundField HeaderText="Observaciones" DataField="OBSERVACIONES" ReadOnly="true" />
                            <asp:BoundField HeaderText="Casa Productora" DataField="CASA_PRODUCTORA" ReadOnly="true" />
                            <asp:BoundField HeaderText="Ubicacion Cinta " DataField="UBICACION_CINTA" ReadOnly="true" />
                            <asp:TemplateField HeaderText="Estado">
                                <ItemTemplate>
                                    <%# (string)Eval("ESTADO")=="COMPLETO" ? "<span class=\"badge bg-success\">COMPLETO</span>" : "<span class=\"badge bg-warning\">EN BLOQUES</span>" %>                                                                       
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <PagerSettings Mode="NumericFirstLast" PageButtonCount="10" />
                    </asp:GridView>
                    </div>
                    <br />
                    <asp:LinkButton ID="btnDescargarPDF" runat="server" CssClass="btn btn-block btn-outline-primary" OnClick="btnDescargarPDF_Click" OnClientClick="limpiarCampos()">
                         <i class="fa fa-download"></i> Descargar PDF
                    </asp:LinkButton>
                    
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
    <!-- /.row -->
    
    <!--modal-content -->
    <div class="modal fade" id="modalBuscar" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Buscar Registros</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="NomBusqueda">Nombre Pelicula:</label>
                        <input runat="server" type="text" class="form-control" id="NomBusqueda" placeholder=""/>
                    </div>
                    <div class="form-group">
                        <label for="FechaBusqueda">Fecha:</label>
                        <input runat="server" type="date" class="form-control" id="FechaBusqueda" data-inputmask-alias="date" data-inputmask-inputformat="dd/mm/yyyy"/>
                    </div>
                    <div class="form-group">
                        <label for="CasaBusqueda">Casa Productora:</label>
                        <input runat="server" type="text" class="form-control" id="CasaBusqueda" placeholder=""/>
                    </div>                  
                    <div class="form-group">
                        <label for="UbicacionBusqueda">Ubicacion Cinta:</label>
                        <input runat="server" type="text" class="form-control" id="UbicacionBusqueda" placeholder=""/>
                    </div>                    
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger" onclick="limpiarFormBusqueda()" data-dismiss="modal">Cancelar</button>
                    <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="btn btn-primary" OnClick="btnBuscar_Click" />
                </div>
            </div>
        </div>
    </div>
    <!-- /.modal-content -->
</asp:Content>
